pointgrey_camera_driver/include/pointgrey_camera_driver/PointGreyCamera.h, pointgrey_camera_driver/src/PointGreyCamera.cpp
Moved the GetCameraInfo calls from grabImage() method. I tested this with PtGrey Flea3 camera. The camera was set to 60fps. The hz of the published image_raw improved from 45hz to 51hz.
=> Fix for issue #27

pointgrey_camera_driver/cfg/PointGrey.cfg, pointgrey_camera_driver/include/pointgrey_camera_driver/PointGreyCamera.h, pointgrey_camera_driver/src/PointGreyCamera.cpp, pointgrey_camera_driver/src/nodelet.cpp, pointgrey_camera_driver/src/stereo_nodelet.cpp
Fix the problem of not being able to set white balance using Property.
When trying to set white balance on my FL3-U3-13E4C-C, both this ros
driver and flycap software cannot set the white balance naturally.
After playing around with the flycap software, I found that I have
to set the highest bit of register 80C (which is white balance) to 1
to enable this feature. So I modified the original SetWhiteBalance to
use WriteRegister directly. And add support for auto white balance.
I currently don't have other pointgrey cameras, so I cannot verify
that this will work for sure. Also, when initially launched, since the 
frame rate is low (7.5hz), it will some time for the auto white balance
to converge to the right values. So the entire image would look green
and gradually become normal.
=> Add auto white balance and fix not able to write white balance

pointgrey_camera_driver/src/nodelet.cpp
Removing check for number of subscribers to publish raw image - there are checks in place in ROS to serialize messages only if necessary. This check leads to frequency warnings
=> Removing check for number of subscribers (in nodelet) to publish raw image

pointgrey_camera_driver/udev/60-pgr.rules
Adds the vendor ID for Startech-brand Firewire interface cards.  This is necessary for accessing the camera(s) connected through the card.
=> Add Startech vendor ID

pointgrey_camera_driver/launch/bumblebee.launch
Without the format7 color coding specified, the driver will crash with the following error:
Reconfigure Callback failed with error: PointGreyCamera::setFormat7 Error validating Format 7 settings | FlyCapture2::ErrorType 22Error setting Format 7 information.
Specifying the coding allows the driver to start up properly.
=> Specify color coding.

pointgrey_camera_driver/cmake/download_flycap
Lately the PTGray support told me that they fixed the problem with multi-camera setups. I have tested it with two Blackfly cameras and i can confirm that #28 is solved in this version. It looks that we can think about updating the SDK.
In this PR SDK is updated for i386 and amd64. I left armv7 as is because i don't have hardware to test it.
=> update flycap SDK to 2.9.3.13

pointgrey_camera_driver/cmake/download_flycap
This updates the download links of the x64 and x86 releases to the new FlyCapture 2.9.3.43 releases. The 2.9.3.13 release has been unpublished, and no release notes are available yet unfortunately. This should fix #64.
Note: The ARM release never worked on our system with our cameras so its link has not been updated.
=> Update to FlyCapture v2.9.3.43

pointgrey_camera_driver/src/PointGreyCamera.cpp, pointgrey_camera_driver/src/nodelet.cpp
This implements the recovery strategy that was commented out, when an exception is thrown.
The strategy does: `disconnect` + `connect` + `start`.
From my tests, there's no need to call `stop` before `disconnect`.
If any of the three steps fail, it's tried again after one second.
From my tests, none of them fails.
I need this because after many hours running the camera, if fails to grab images or query the temperature property in the `devicePoll` loop:
https://github.com/ros-drivers/pointgrey_camera_driver/blob/master/pointgrey_camera_driver/src/nodelet.cpp#L315
Since it's very difficult to reproduce, I've forced an error to happen every 10 iterations, when the `TEMPERATURE` property is read, with this code diff:
``` diff
diff --git a/pointgrey_camera_driver/src/PointGreyCamera.cpp …
```
=> Reconnect on error

pointgrey_camera_driver/src/PointGreyCamera.cpp
This allows to use the mode4 which corresponds to a 2x2 binning. Example: an image of 1000x800 becomes an image of 500x400. I tested on a flea usb 3.0 camera.
=> Added the option to use the format7_mode4. 

pointgrey_camera_driver/cfg/PointGrey.cfg
```Format7_Mode4``` is implemented in pull request #84, but it is not yet added to dynamic reconfigure. This pull request adds ```Format7_Mode4``` to ```video_mode``` in dynamic reconfigure. 
Tested with FL3-U3-32S2C.
Please review and provide feedback.
=> Added video_mode Format7_Mode4 option in dynamic reconfigure

pointgrey_camera_driver/src/PointGreyCamera.cpp
Without this this, we've found that the Chameleon 3 tends to get stuck with a 'green screen' and is not able to adjust the white balance to a reasonable setting.
With this change, auto white balance continues to work using the values in the configuration file as default instead of zeros and auto white balance can be toggled on and off.
=> Improve white balance initialisation and logic.

pointgrey_camera_driver/src/PointGreyCamera.cpp, pointgrey_camera_driver/src/nodelet.cpp
I don't know if it makes sense or not. But I found myself struggling with the following thing:
"why the camera_info is not being published"
I discovered that if nothing is subscribed to the image published by the camera the camera_info will not be published. Ok, this can make sense but at least I think the user needs an INFO about it. 
what do you think ?
=> Added a NODELET_INFO to inform the user about the camera_info topic

pointgrey_camera_driver/cfg/PointGrey.cfg, pointgrey_camera_driver/src/PointGreyCamera.cpp
This adds the ability to set a strobe on GPIO2. This is the preferred pin for all none-flea cameras [according to PointGrey ](http://www.ptgrey.com/KB/11052) (where as Flea cameras use the existing hardcoded GPIO1).
Not as elegant as having a [universally settable GPIO pin](https://github.com/ros-drivers/pointgrey_camera_driver/pull/80), but it won't break anyone's code who is depending on that hard coded GPIO1.
=> Add option to strobe on GPIO2.

pointgrey_camera_driver/src/PointGreyCamera.cpp
ROS (at least kinetic) seems to support bayer 16bit without any problem.
=> Enabling 16bit Bayer format

pointgrey_camera_driver/src/PointGreyCamera.cpp
On most of my cameras the packet resend option is not enabled by default while it is a big improvement in general (packet drop, isochronous problems, frame integrity issues, etc).
=> Enabling GigE packet resend by default

pointgrey_camera_driver/cmake/TargetArch.cmake, pointgrey_camera_driver/cmake/download_flycap
I have add the new download link for aarch64 processor such as jetson TX1
=> Add flycapture2 lib download rule for aarch64(e.g. Jetson TX1)

pointgrey_camera_driver/CMakeLists.txt
Build failure when pointgrey_camera_driver is installed in ```/opt/ros``` and built from source in a user's workspace. The workspace source code will find ```libflycapture.so.2``` in ``/opt/ros```, but the header files are missing.
This is solved by requiring the file ```flycapture/FlyCapture2.h``` as well.
=> Download flycapture if header files are missing

pointgrey_camera_driver/cfg/PointGrey.cfg, pointgrey_camera_driver/launch/camera.launch, pointgrey_camera_driver/src/PointGreyCamera.cpp
RGB8 format is not supported in the current driver, which caused dark images when using the camera outdoors. I added RGB8 pixel format to enable the camera to control the saturation and sharpness of the image as well and hence improved the quality of the images.
=> Added support to RGB8 pixel format and controls for sharpness and saturation

pointgrey_camera_driver/CMakeLists.txt
This fixes an issue with not finding the library/headers at build time when already installed on the system.
FYI @v-mehta
=> Use find_path to look for system headers.

pointgrey_camera_driver/include/pointgrey_camera_driver/camera_exceptions.h, pointgrey_camera_driver/src/PointGreyCamera.cpp, pointgrey_camera_driver/src/nodelet.cpp
Hi!
I added an exception for error 41, consistency exception. These errors happen once in a while using GigE cameras. 
I see no reason why it would have to re-connect to camera when we get this error from flycapture. Correct?
=> Not closing connection when consistency exception happens.

pointgrey_camera_driver/src/nodelet.cpp, pointgrey_camera_driver/src/stereo_nodelet.cpp
These macros, deprecated for now 8 years, will be removed in the next ROS release (ROS Melodic)
This change will allow the code to keep compiling on future ROS versions
=> update to use non deprecated pluginlib macro
